
name: 'DataEngineering'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  DataEngineering:
    staging:
      +database: CPD_SILVER_DB
      +schema: staging
      +materialized: view
    
    marts:
      +database: CPD_GOLD_DB
      +schema: marts
      +materialized: table
